[package]
name = "fe-test-utils"
version = "26.0.0-alpha.5"
edition.workspace = true

[lib]
doctest = false

[dependencies]
insta = { default-features = false, version = "1.42" }
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-tree.workspace = true
url.workspace = true
