[package]
name = "fe-bench"
version = "26.0.0-alpha.5"
edition.workspace = true

[dev-dependencies]
criterion = "0.5"
walkdir = "2.4"

[dependencies]
driver.workspace = true
parser.workspace = true
common.workspace = true
camino.workspace = true
url.workspace = true
tracing.workspace = true

[[bench]]
name = "analysis"
harness = false
